### ISSUE TITLE
Art: Main Character

### ISSUE THREAD

**Issue by joelll55** [4BMStudios/2d-game#1]
This should be the the base main character with no equipped items

- Needs to have all the animations done too, such as walking and running etc...

**Comment by KenDucken** [comment]
i am almost done
i have 90% completed the front moving onto other angles now

**Comment by KenDucken** [comment]
angles are hard

**Comment by joelll55** [comment]
@KenDucken hurry up with this

**Comment by KenDucken** [comment]
![Image](https://github.com/4BMStudios/2d-game/assets/144667258/0539cb8c-bd76-4372-94d8-d2a711f2a40c)

**Comment by KenDucken** [comment]
actually before i close this imma change his hair
i don't like how similar the colour is to the shoes
