### ISSUE TITLE
Art: Main Menu Design

### ISSUE THREAD

**Issue by TomAndJerrys2** [4BMStudios/2d-game#8]
This is what the user will first see after launching the game. Should have buttons: Play (brings to New Game/Load Game buttons), Settings, Exit

- [x] Concept
- [x] Background

**Comment by joelll55** [comment]
**Sketches of main menu + background**

# Background concept

![Image](https://github.com/4BMStudios/2d-game/assets/139919096/1d2c99c5-0158-4d12-96f5-baf6e42fd84f)

# Design 1

![Image](https://github.com/4BMStudios/2d-game/assets/139919096/46aca0ec-e305-400c-a1b6-db2a1ca31be3)

# Design 2

![Image](https://github.com/4BMStudios/2d-game/assets/139919096/49e02eb9-3471-4053-bbf1-cb4669a1747f)

(after pressing play)
- buttons will slide/fade in from side

![Image](https://github.com/4BMStudios/2d-game/assets/139919096/bec18197-ec49-4fb3-8451-53f1b2a756ce)

**Comment by Ezraliss800** [comment]
Main Menu Game Art : 
![MAIN MENU GAMEART](https://github.com/4BMStudios/2d-game/assets/80759979/42185c1e-781d-4663-bfe5-43a946d8ee83)

**Comment by joelll55** [comment]
Menu button designs:


![Image](https://github.com/4BMStudios/2d-game/assets/139919096/6ea8fcad-4cff-4cec-9ccb-23b9c93dd9eb)


![Image](https://github.com/4BMStudios/2d-game/assets/139919096/a88de911-e04b-43f7-bb43-bc8c41b9e1c7)

![Image](https://github.com/4BMStudios/2d-game/assets/139919096/8d491008-d873-4f00-9e35-a87e41f63177)

![Image](https://github.com/4BMStudios/2d-game/assets/139919096/48b47671-3e00-4f28-8704-4ae05e56e3ed)

**Comment by joelll55** [comment]
wider

![Image](https://github.com/4BMStudios/2d-game/assets/139919096/a941ae35-9163-4e4b-87fb-fe2d5f9a6894)
![Image](https://github.com/4BMStudios/2d-game/assets/139919096/ae715b69-25dd-4bde-9dd4-56d3c45fc0bd)
![Image](https://github.com/4BMStudios/2d-game/assets/139919096/9dab59c3-feac-427f-93e6-82bf60f655c4)
![Image](https://github.com/4BMStudios/2d-game/assets/139919096/fa54d51e-9b01-46e6-aeed-409c606efdb8)

**Comment by joelll55** [comment]
![Image](https://github.com/4BMStudios/2d-game/assets/139919096/6319497a-f36e-4ad9-9150-4d6de9ea1ff2)
